name: CI-CD
on:
  push:
    branches: ["main"]
    workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter codigo"
      - run: echo "Executar o docker build"
      - run: echo "Enviar a imagem Docker para Docker Hub"
  CD:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter codigo"
      - run: echo "configurar kubeconfig"
      - run: echo "Executar o Apply"
         
    
